[build-system]
requires = [
    "setuptools>=60",
    "wheel",
    "setuptools-scm>=8.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = 'no-local-version'
version_file = "src/h5analysis/_version.py"